// Code generated by scripts/generate-row-types.mjs. DO NOT EDIT.

export const EVENT_CATEGORIES = [
  "club",
  "academic",
  "social",
  "career",
  "sports",
  "arts",
  "community",
  "free_food",
] as const;
export type EventCategory = (typeof EVENT_CATEGORIES)[number];
export const EVENT_SOURCES = [
  "instagram",
  "highlander_link",
  "campus_website",
  "club_website",
  "manual",
] as const;
export type EventSource = (typeof EVENT_SOURCES)[number];

/** Generated from https://highlanderhub.local/schemas/events.upsert.schema.json — do not edit by hand. */
export interface EventRow {
  id: string;
  title: string;
  description: string;
  starts_at: string;
  ends_at?: string | null;
  location: string;
  host: string;
  host_handle?: string | null;
  category: "club" | "academic" | "social" | "career" | "sports" | "arts" | "community" | "free_food";
  tags: string[];
  source: "instagram" | "highlander_link" | "campus_website" | "club_website" | "manual";
  source_url?: string | null;
  image_url?: string | null;
  is_free: boolean;
  rsvp_required: boolean;
  rsvp_url?: string | null;
  scraped_at: string;
}

/** Generated from https://highlanderhub.local/schemas/stories.upsert.schema.json — do not edit by hand. */
export interface StoryRow {
  id: string;
  handle: string;
  account_label?: string | null;
  account_category?: string | null;
  owner_userid?: number | null;
  owner_username?: string | null;
  typename?: string | null;
  is_video: boolean;
  posted_at: string;
  expires_at?: string | null;
  image_url?: string | null;
  video_url?: string | null;
  caption?: string | null;
  caption_mentions: string[];
  story_cta_url?: string | null;
  permalink?: string | null;
}
